import {ApiProperty} from "@nestjs/swagger";
import {$Enums, User as PrismaUser} from "@repo/database"
import Role = $Enums.Role;


export class User implements PrismaUser {
    @ApiProperty({
        description: "User Id, generated by uuid",
        nullable: false,
        required: true,
        type: "string",
        example: "2313w49-0db7-4v79-aacc-52624343bf2t",
    })
    id: string;

    @ApiProperty({
        description: "First Name",
        nullable: false,
        required: true,
        type: "string",
        example: "Ivan",
    })
    firstName: string;

    @ApiProperty({
        description: "Last Name",
        nullable: false,
        required: true,
        type: "string",
        example: "Ivanov",
    })
    lastName: string;

    @ApiProperty({
        description: "Email",
        uniqueItems: true,
        nullable: false,
        required: true,
        type: "string",
        example: "youremail@example.com",
    })
    email: string;

    @ApiProperty({
        description: "Email Verified",
        nullable: true,
        required: false,
        type: "string",
        example: "2022-01-01T00:00:00.000Z",
    })
    emailVerified: Date;

    @ApiProperty({
        description: "Password: Min 6 characters, 1 uppercase, 1 lowercase and 1 number",
        nullable: false,
        required: true,
        type: "string",
        example: "Password123",
    })
    password: string;

    @ApiProperty({
        description: "User Role (admin, user)",
        nullable: false,
        required: true,
        type: "string",
        example: "user",
    })
    role: Role;

    @ApiProperty({
        description: "Avatar URL",
        nullable: true,
        required: false,
        type: "string",
        example: "https://example.com/avatar.jpg",
    })
    avatar: string;

    @ApiProperty({
        description: "Account creation date",
        type: "string",
        format: "date-time",
        example: "2024-01-01T00:00:00.000Z",
    })
    createdAt: Date;

    @ApiProperty({
        description: "Last update date",
        type: "string",
        format: "date-time",
        example: "2024-01-01T00:00:00.000Z",
    })
    updatedAt: Date;


    // @ApiProperty({
    //     description: "Phone number",
    //     nullable: true,
    //     required: false,
    //     type: "string",
    //     example: "+1234567890",
    // })
    // phone: string;
    //
    // @ApiProperty({
    //     description: "Two-factor authentication status",
    //     type: "boolean",
    //     example: false,
    // })
    // twoFactorEnabled: boolean;
    //
    // @ApiProperty({
    //     description: "Last login date",
    //     nullable: true,
    //     type: "string",
    //     format: "date-time",
    //     example: "2024-01-01T00:00:00.000Z",
    // })
    // lastLoginAt: Date;
}